---
# tasks file for openshift-content-mirror

# dont bother checksumming for now, for some reason they dont store or generate all the sums needed to automate this cleanly.

# - name: Download OC Checksum File
#   get_url:
#     url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/sha256sum.txt"
#     dest: "{{ dest }}/sha256sum.txt"
#     mode: '0440'
#   register: checksum_file
#
# - name: Remove Versions from Checksum File
#   replace:
#     path: "{{ checksum_file.dest }}"
#     regexp: '-(\d+)\.(\d+)\.(\d+)'
#     replace: ''

# - name: Set Working Directory
#   shell: |
#     pwd
#   register: working_dir
#   changed_when: false #stat conditional makes this idempotent, check molcule issue board for details

- name: "Download OC Binary {{ ocp_version }}"
  get_url: 
    url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/{{ ocp_version }}/{{ os_platforms[os_platform] }}"
    dest: "/tmp/"
    mode: '0660'
    checksum: "sha256:https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/{{ ocp_version }}/sha256sum.txt"
  register: oc_binary_tarball

- name: Extract OC Binary
  unarchive:
    src: "{{ oc_binary_tarball.dest }}"
    #dest: "{{ working_dir.stdout }}/{{ dest }}"
    dest: "/tmp/"
    remote_src: yes
  register: oc_binary

- name: Creating bin directory
  file:
    path: "{{ dest }}/bin"
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: Copy Contents of OC Binary to Bundle
  copy:
    src: "/tmp/{{ item }}"
    dest: "{{ dest }}/bin"
    mode: '0550'
    remote_src: yes
  loop:
    - kubectl
    - oc

- name: Check if Openshift Content already exists
  stat:
    path: "{{ dest }}/openshift-release-dev"
  register: openshift_content

- name: Download OC-MIRROR Binary
  get_url: 
    url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/oc-mirror.tar.gz"
    dest: "/tmp/"
    mode: '0660'
#    checksum: "sha256:https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/sha256sum.txt"
  register: oc_mirror_binary_tarball

- name: Extract OC-MIRROR Binary
  unarchive:
    src: "{{ oc_mirror_binary_tarball.dest }}"
    #dest: "{{ working_dir.stdout }}/{{ dest }}"
    dest: "/tmp/"
    remote_src: yes
  register: oc_mirror_binary

- name: Copy Contents of OC Binary to Bundle
  copy:
    src: "/tmp/{{ item }}"
    dest: "{{ dest }}/bin"
    mode: '0550'
    remote_src: yes
  loop:
    - oc-mirror


- name: Creating oc-mirror template
  template:
    src: image-config.j2
    dest: /tmp/image-config.yaml

- name: "Mirroring Openshift Images for OCP Version [ {{ ocp_version }} ]"
  shell: |
    {{ dest }}/bin/oc-mirror --config /tmp/image-config.yaml file://{{ dest }}/openshift-release-dev
      
# - name: Mirror Openshift 4 Content Locally
#   shell: |
#     {{ dest }}/oc adm release mirror --insecure=true \
#     --to-dir={{ dest }}/openshift-release-dev \
#     -a {{ pull_secret_file }} \
#     quay.io/openshift-release-dev/ocp-release:{{ ocp_version }}-x86_64
#   when: openshift_content.stat.exists == false
#   changed_when: false #stat conditional makes this idempotent, check molcule issue board for details

- name: Check if Openshift Install Binary already exists
  stat:
    path: "{{ dest }}/bin/oc"
  register: openshift_oc_binary

- name: Extract oc CLI Binary From Content
  shell: |
    {{ dest }}/bin/oc adm release extract -a {{ pull_secret_file }} \
    --command=oc --to={{ dest }}/bin \
    quay.io/openshift-release-dev/ocp-release:{{ ocp_version }}-x86_64
  when: openshift_oc_binary.stat.exists == false
  changed_when: false #stat conditional makes this idempotent, check molcule issue board for details

- name: Check if Openshift Install Binary already exists
  stat:
    path: "{{ dest }}/bin/openshift-install"
  register: openshift_install_binary

- name: Extract openshift-install Binary From Content
  shell: |
    {{ dest }}/bin/oc adm release extract -a {{ pull_secret_file }} \
    --command=openshift-install --to={{ dest }}/bin \
    quay.io/openshift-release-dev/ocp-release:{{ ocp_version }}-x86_64
  when: openshift_install_binary.stat.exists == false
  changed_when: false #stat conditional makes this idempotent, check molcule issue board for details

- name: Make Container Image Subdirectory
  file:
    path: "{{ dest }}/containers"
    state: directory

- name: Download NGINX and Registry Images into Package
  get_url:
    url: "{{ item }}"
    dest: "{{ dest }}/containers/"
    mode: '0660'
  register: containers
  loop: "{{ container_files }}"

- name: "Download mirror-registry Binary"
  get_url: 
    url: "https://developers.redhat.com/content-gateway/rest/mirror2/pub/openshift-v4/clients/mirror-registry/latest/mirror-registry.tar.gz"
    dest: "{{ dest }}/containers/"
    mode: '0660'
    checksum: "sha256:https://developers.redhat.com/content-gateway/rest/mirror2/pub/openshift-v4/clients/mirror-registry/latest/sha256sum.txt"
  register: mirror_registry_binary_tarball

- name: "Creating bundle manifest file"
  template:
    src: bundle-manifest.j2
    dest: /tmp/bundle-manifest.yaml
  
- name: Copy manifest file
  ansible.builtin.copy:
    src: /tmp/bundle-manifest.yaml
    dest: "{{ dest }}/bin"
    mode: '0644'

- name: Copy oc-mirror config file
  ansible.builtin.copy:
    src: /tmp/mirror-config.yaml
    dest: "{{ dest }}/bin"
    mode: '0644'
