---
- name: Generate Openshift Bundle
  hosts: localhost
  connection: local

  vars_prompt:

    - name: destination
      prompt: "Desired path to dump operator content content (example: /home/user1/bundle/rh-operators)"
      default: "./operators/community-operators"
      private: false

    - name: desired_ocp_version
      prompt: "Major version of OpenShift (example: 4.10)"
      default: "4.11"
      private: false

    - name: desired_community_operators
      prompt: "Desired Openshift community-operators "
      private: false

    - name: desired_archive_size
      prompt: Maximum size (GiB) of each archive
      default: "4"
      private: false

  pre_tasks:
    - name: Generate | include rhoperator-facts-setup
      ansible.builtin.import_tasks: 'ansible/playbooks/rhoperator-facts-setup.yml'
    - name: Generate | include pretasks
      ansible.builtin.import_tasks: 'ansible/playbooks/rhoperator-pretasks.yml'

  roles:
    - role: community-operators
      vars:
        dest: "{{ destination }}"
        operators: "[{{ desired_community_operators }}]"
        ocp_version: "{{ desired_ocp_version }}"
        archive_size: "{{ desired_archive_size }}"
