---
- name: Generate Openshift Bundle
  hosts: localhost
  connection: local

  vars_prompt:
    - name: source_bundle_dir
      prompt: "Enter source bundle dir:  "
      default: "~/work/bundle"
      private: no

  roles:
    - role: create-ocp-bundles 
