---
- name: Generate Openshift Bundle
  hosts: localhost
  connection: local

  vars_prompt:

    - name: destination
      prompt: "Desired path to dump content (example: /home/user1/bundle)"
      private: no

    - name: cloud_selection
      prompt: Cloud to generate content for (aws,gcp,azure,metal,rhv,vmware,openstack)
      default: "aws"
      private: no

    - name: pull_secret_path
      prompt: "Path to your Pull Secret file (example: /home/user1/pull_secret.txt)"
      private: no

    - name: desired_os_platform
      prompt: Desired Operating System Platform for execution (linux,macos,windows)
      default: "linux"
      private: no

    - name: desired_ocp_version
      prompt: Desired Openshift Version
      default: "4.6.8"
      private: no

    - name: desired_archive_size
      prompt: Maximum size (GiB) of each archive
      default: "4"
      private: no

  pre_tasks:
  - name: generate | include facts-setup
    ansible.builtin.import_tasks: 'ansible/playbooks/facts-setup.yml'
  - name: generate | include pretasks
    vars:
      stable_version: false  
    ansible.builtin.import_tasks: 'ansible/playbooks/pretasks.yml'

  roles:
    - role: rhcos-image-download
      vars:
        dest: "{{ destination }}"
        cloud_target: "{{ cloud_selection }}"
    - role: openshift-content-mirror
      vars:
        dest: "{{ destination }}"
        pull_secret_file: "{{ pull_secret_path }}"
        os_platform: "{{ desired_os_platform }}"
        ocp_channel: "{{ desired_ocp_version }}"
        archive_size: "{{ desired_archive_size }}"
    - role: cloud-dependencies
      vars:
        cloud_target: "{{ cloud_selection }}"
        dest: "{{ destination }}"
        os_platform: "{{ desired_os_platform }}"
