---
- name: Download AWS CLI Binary
  ansible.builtin.get_url:
    url: "{{ cloud_targets.aws.tool_urls[ os_platform ] }}"
    dest: "{{ directory }}"
    mode: '0640'
  register: awscli_binary

- name: Copy in AWS IAM Templates
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ directory }}"
  loop: "{{ cloud_targets.aws.files }}"
