---
# tasks file for cloud-dependencies
- name: Build a cloud-dependencies Folder
  file:
    path: "{{ dest }}/cloud-dependencies"
    state: directory

- include_tasks: aws.yml
  when: cloud_target == 'aws'

- include_tasks: azure.yml
  when: cloud_target == 'azure'

- include_tasks: gcp.yml
  when: cloud_target == 'gcp'
