---
# tasks file for community-operators
- name: Parameters passed
  ansible.builtin.debug:
    msg: "dest: {{ dest }} operators: {{ operators }} ocp_version: {{ ocp_version }} archive_size: {{ archive_size }}"

- name: "Creating {{ dest }}/operators/community directory"
  ansible.builtin.file:
    path: "{{ dest }}/operators/community"
    state: directory

- name: Creating oc-mirror redhat operator template
  ansible.builtin.template:
    src: community-operator-images.j2
    dest: /tmp/community-operator-images.yaml

- name: "Mirroring Community operator Images for OCP Version [ {{ ocp_version }} ]"
  ansible.builtin.shell: |
    oc-mirror --config /tmp/community-operator-images.yaml file://{{ dest }}/operators/community
  register: oc_mirror_rc

- name: Debug oc-mirror output
  ansible.builtin.debug:
    var: oc_mirror_rc
