# This config uses the headsOnly feature which will mirror the
# latest version of each channel within each package contained
# within a specified operator catalog
---
#apiVersion: mirror.openshift.io/v1alpha2
#kind: ImageSetConfiguration
#mirror:
#  operators:
#    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.11
#    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.10
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
archiveSize: 4
mirror:
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.11
      packages:
        - name: advanced-cluster-management
          channels: 
          - name: release-2.6
        - name: openshift-gitops-operator
          channels: 
          - name: stable
    - catalog: registry.redhat.io/redhat/community-operator-index:v4.11
      packages:
        - name: patterns-operator
          channels: 
          - name: fast
storageConfig:
  local:
    path: /home/claudiol/work/bundle/operators 
