---
# tasks file for create-ocp-bundles

- name: Create Self-Extracting binary bundle
  ansible.builtin.shell: "{{ role_path }}/build/create-ocp-bin-distro.sh -d {{ source_bundle_dir }} -r {{ role_path }}"
  register: r_bin_distro

- name: binary bundle debug
  debug:
    var: r_bin_distro

- name: Create Self-Extracting ImageSet bundle
  ansible.builtin.shell: "{{ role_path }}/build/create-ocp-mirror-distro.sh -d {{ source_bundle_dir }} -r {{ role_path }}"
  register: r_mirror_distro

- name: Create Self-Extracting Containers bundle
  ansible.builtin.shell: "{{ role_path }}/build/create-ocp-containers-distro.sh -d {{ source_bundle_dir }} -r {{ role_path }}"
  register: r_containers_distro

- name: Create Self-Extracting CloudCLI bundle
  ansible.builtin.shell: "{{ role_path }}/build/create-cloud-distro.sh -d {{ source_bundle_dir }} -r {{ role_path }}"
  register: r_cloud_distro
