name: RHV Bundle
on:
# this will run on each merge to main/master
  push:
    branches:
    - rhv
    tags:
    - '*'

# this will run when latest code is published in this repo
  # release:
  #   types: [published]

jobs:
  
  # this is where the heavy lifting occurs
  generate_rhv_bundle:
    name: Generate RHV Bundle
    runs-on: [self-hosted, Linux]
    env:
      PULL_SECRET: ${{ secrets.PULL_SECRET }}
      OCP_VERSION: ${{ secrets.OCP_VERSION }}
    steps:

      - name: Checkout current branch
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Clean and Prepare
        run: |
          rm -rf {rhv-content,rhv}
          mkdir -p {rhv-content,rhv}
          rm -f /tmp/pull_secret.txt
          echo $PULL_SECRET > /tmp/pull_secret.txt

      - name: Write Variables File
        run: |
          cat > gh_actions_variables.yml << EOF
          ocp_version: $OCP_VERSION
          pull_secret_path: /tmp/pull_secret.txt
          os_platform: linux
          destination: rhv-content
          cloud_selection: rhv
          EOF

      - name: Generate Bundle Content
        run: |
          ansible-playbook generate.yml --extra-vars "@gh_actions_variables.yml"

      - name: Compress and Package Content
        run: |
          tar -czvf rhv/openshift4-rhv-linux-$OCP_VERSION-x86_64.tar.gz rhv-content/*


  # checksum the file and prepare for upload
  validate_rhv_bundle:
    name: Validate RHV Bundle
    runs-on: [self-hosted, Linux]
    needs: generate_rhv_bundle
    steps:

      - name: Checksum File
        run: |
          rm -f rhv/sha256sum.txt
          (sha256sum rhv/* | sed 's, .*/, ,') > rhv-content/sha256sum.txt
          mv rhv-content/sha256sum.txt rhv/

  # this will upload whatever is in the local rhv directory to the remote rhv directory in the S3 bucket.
  upload_rhv_bundle:
    name: Upload RHV Bundle
    needs: validate_rhv_bundle
    runs-on: [self-hosted, Linux]
    steps:
    - uses: jakejarvis/s3-sync-action@master
      with: 
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-2'   # optional: defaults to us-east-1
        SOURCE_DIR: 'rhv/'      # optional: defaults to entire repository
        DEST_DIR: 'rhv'
